apiVersion: v2
name: dependencies
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: argo
  version: 0.9.8
  repository: "https://argoproj.github.io/argo-helm"
  alias: argowf
